__title__ = 'yaxil'
__description__ = 'Yet another XNAT interface libary'
__url__ = 'https://github.com/harvard-nrg/yaxil'
__version__ = '0.5.2'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
